### ISSUE TITLE
Wallet app crashes when switching to tesnet

### ISSUE THREAD

**Issue by zlumer** [CityOfZion/neon-wallet#1136]
**Wallet version or commit SHA:**
Wallet version 0.2.5 (a1ac1d5)

**Environment:**
Win 10 Pro N (64 bit) Version 1803 Build 17134.48

**Prerequisites:**
Make sure you have at least one wallet saved.

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your saved wallet from the combobox.
4. Enter your wallet password.
5. Click "Login"

Up until this step everything should be fine, you should be able to login to mainnet wallet successfully.

6. Click on "MainNet/TestNet" combobox.
7. Select "TestNet".

Expected: app should switch to testnet.
Instead, app crashes with blank screen.

Error logs:

```
bundle.js:60 Error: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at p (bundle.js:60)
    at er (bundle.js:60)
    at bundle.js:60
    at a (bundle.js:60)
    at i (bundle.js:60)
    at beginWork (bundle.js:60)
    at r (bundle.js:60)
    at i (bundle.js:60)
    at a (bundle.js:60)
    at _ (bundle.js:60)
u @ bundle.js:60
bundle.js:60 uncaught at n Invariant Violation: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at p (file:///C:/Users/zlume/AppData/Local/Programs/Neon/resources/app.asar/app/dist/bundle.js:60:316)
    at er (file:///C:/Users/zlume/AppData/Local/Programs/Neon/resources/app.asar/app/dist/bundle.js:60:34548)
    at file:///C:/Users/zlume/AppData/Local/Programs/Neon/resources/app.asar/app/dist/bundle.js:60:42579
    at a (file:///C:/Users/zlume/AppData/Local/Programs/Neon/resources/app.asar/app/dist/bundle.js:60:44060)
    at i (file:///C:/Users/zlume/AppData/Local/Programs/Neon/resources/app.asar/app/dist/bundle.js:60:43961)
    at beginWork (file:///C:/Users/zlume/AppData/Local/Programs/Neon/resources/app.asar/app/dist/bundle.js:60:48506)
    at r (file:///C:/Users/zlume/AppData/Local/Programs/Neon/resources/app.asar/app/dist/bundle.js:60:52586)
    at i (file:///C:/Users/zlume/AppData/Local/Programs/Neon/resources/app.asar/app/dist/bundle.js:60:52906)
    at a (file:///C:/Users/zlume/AppData/Local/Programs/Neon/resources/app.asar/app/dist/bundle.js:60:53142)
    at _ (file:///C:/Users/zlume/AppData/Local/Programs/Neon/resources/app.asar/app/dist/bundle.js:60:56476)
N @ bundle.js:60
```

**Comment by drptbl** [comment]
We're aware of this, it's caused because TestNet is resyncing currently.
Going more in-depth details, it's because `https://neoscan-testnet.io/api/test_net/v1/get_height` returns:
```
{"height":null}
```
However wallet should handle this case anyway, and that's why I've already created an issue for this, here:
https://github.com/CityOfZion/neon-wallet/issues/1128
^ after this one is fixed, it shouldn't crash the wallet anymore if it occurs again.

Thanks for reporting 👍.
