### ISSUE TITLE
Unable to build node-sass as part of 'yarn install' on Mac OSX

### ISSUE THREAD

**Issue by m-roberts** [CityOfZion/neon-wallet#281]
I am trying to test the functionality in [this pull request](https://github.com/CityOfZion/neon-wallet/pull/244), which is not in a release yet.

When I do a fresh repository clone and run `yarn install` on Mac OSX, I get [this output](https://pastebin.com/G9pJufEw).

From what I can tell, the problem is in installing node-sass, which fails here:

```
  rm -f Release/sass.a && ./gyp-mac-tool filter-libtool libtool  -static -o Release/sass.a Release/obj.target/libsass/src/libsass/src/ast.o Release/obj.target/libsass/src/libsass/src/base64vlq.o Release/obj.target/libsass/src/libsass/src/bind.o Release/obj.target/libsass/src/libsass/src/cencode.o Release/obj.target/libsass/src/libsass/src/color_maps.o Release/obj.target/libsass/src/libsass/src/constants.o Release/obj.target/libsass/src/libsass/src/context.o Release/obj.target/libsass/src/libsass/src/cssize.o Release/obj.target/libsass/src/libsass/src/emitter.o Release/obj.target/libsass/src/libsass/src/environment.o Release/obj.target/libsass/src/libsass/src/error_handling.o Release/obj.target/libsass/src/libsass/src/eval.o Release/obj.target/libsass/src/libsass/src/expand.o Release/obj.target/libsass/src/libsass/src/extend.o Release/obj.target/libsass/src/libsass/src/file.o Release/obj.target/libsass/src/libsass/src/functions.o Release/obj.target/libsass/src/libsass/src/inspect.o Release/obj.target/libsass/src/libsass/src/json.o Release/obj.target/libsass/src/libsass/src/lexer.o Release/obj.target/libsass/src/libsass/src/listize.o Release/obj.target/libsass/src/libsass/src/memory_manager.o Release/obj.target/libsass/src/libsass/src/node.o Release/obj.target/libsass/src/libsass/src/output.o Release/obj.target/libsass/src/libsass/src/parser.o Release/obj.target/libsass/src/libsass/src/plugins.o Release/obj.target/libsass/src/libsass/src/position.o Release/obj.target/libsass/src/libsass/src/prelexer.o Release/obj.target/libsass/src/libsass/src/remove_placeholders.o Release/obj.target/libsass/src/libsass/src/sass.o Release/obj.target/libsass/src/libsass/src/sass2scss.o Release/obj.target/libsass/src/libsass/src/sass_context.o Release/obj.target/libsass/src/libsass/src/sass_functions.o Release/obj.target/libsass/src/libsass/src/sass_util.o Release/obj.target/libsass/src/libsass/src/sass_values.o Release/obj.target/libsass/src/libsass/src/source_map.o Release/obj.target/libsass/src/libsass/src/to_c.o Release/obj.target/libsass/src/libsass/src/to_value.o Release/obj.target/libsass/src/libsass/src/units.o Release/obj.target/libsass/src/libsass/src/utf8_string.o Release/obj.target/libsass/src/libsass/src/util.o Release/obj.target/libsass/src/libsass/src/values.o
Usage: /usr/local/bin/libtool [OPTION]... [MODE-ARG]...
Try 'libtool --help' for more information.
libtool:   error: unrecognised option: '-static'
make: *** [Release/sass.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/personal/neon-wallet/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/8.8.1/bin/node" "/Users/personal/neon-wallet/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/personal/neon-wallet/node_modules/node-sass
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

It seems to be a problem with my libtool, but I have made sure that it is the latest available on `brew`. Is there a workaround or fix for this issue?

**Comment by Satoshinaire** [comment]
@m-roberts Is it possible you need to update the Xcode CLI Tools?

**Comment by m-roberts** [comment]
@Satoshinaire just checked on the App Store, and there are no available updates. I also did a `brew upgrade` to make sure that I was on the latest tools installed via Homebrew.

**Comment by Satoshinaire** [comment]
@m-roberts Did you try opening Xcode and checking there for updated CLI tools?

**Comment by m-roberts** [comment]
I can't find anything in Xcode to check for CLI tools updates.

I tried instead to do it via the terminal - running `xcode-select --install` gives this response:
`xcode-select: error: command line tools are already installed, use "Software Update" to install updates`.

Typing "Software Update" into Spotlight suggests going to the App Store, where there are no updates available.

**Comment by Satoshinaire** [comment]
@m-roberts It may not be the issue anyway, I guess. But I had to actually log into the Apple Developer dashboard and check there where I saw Xcode CLI Tools for 10.13 once I updated to High Sierra.

**Comment by m-roberts** [comment]
Ah, that'll be why  - I still need to update to High Sierra. I will do that, update my Xcode CLI tools and report back.

**Comment by m-roberts** [comment]
I found the problem: libtool was no longer pointing to Xcode. Some misconfiguration in brew meant that it was calling `/usr/local/Cellar/libtool/2.4.6_1/bin/glibtool`
