### ISSUE TITLE
yarn install fails on Windows 10

### ISSUE THREAD

**Issue by sgehrman** [CityOfZion/neon-wallet#294]
$ yarn install
yarn install v1.2.1
warning You are using Node "9.0.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"
[1/4] Resolving packages...
success Already up-to-date.
$ electron-builder install-app-deps && electron-rebuild --force --module_dir . -w node-hid -v 1.7.9
electron-builder 19.37.2
Rebuilding native production dependencies for win32:x64
Rebuilding native dependency node-hid
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.0.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "c:\Users\Steve\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (f:\Github\neon-wallet\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (f:\Github\neon-wallet\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at f:\Github\neon-wallet\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "c:\\Program Files\\nodejs\\node.exe" "f:\\Github\\neon-wallet\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.7.9" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd f:\Github\neon-wallet\node_modules\node-hid
gyp ERR! node -v v9.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.0.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "c:\Users\Steve\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (f:\Github\neon-wallet\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (f:\Github\neon-wallet\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at f:\Github\neon-wallet\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "c:\\Program Files\\nodejs\\node.exe" "f:\\Github\\neon-wallet\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.7.9" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd f:\Github\neon-wallet\node_modules\node-hid
gyp ERR! node -v v9.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (f:\Github\neon-wallet\node_modules\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (f:\Github\neon-wallet\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.error (f:\Github\neon-wallet\node_modules\rxjs\Subscriber.js:197:26)
    at Subscriber._error (f:\Github\neon-wallet\node_modules\rxjs\Subscriber.js:128:26)
    at Subscriber.error (f:\Github\neon-wallet\node_modules\rxjs\Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (f:\Github\neon-wallet\node_modules\rxjs\Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (f:\Github\neon-wallet\node_modules\rxjs\Subscriber.js:102:18)
    at SafeSubscriber._next (f:\Github\neon-wallet\node_modules\spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrUnsub (f:\Github\neon-wallet\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.next (f:\Github\neon-wallet\node_modules\rxjs\Subscriber.js:185:22)
error Command failed with exit code 4294967295.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by sgehrman** [comment]
had to do this:

Install all the required tools and configurations using Microsoft's windows-build-tools using npm install --global --production windows-build-tools from an elevated PowerShell or CMD.exe (run as Administrator).
