### ISSUE TITLE
dev branch: GAS and NEO errors

### ISSUE THREAD

**Issue by brianlenz** [CityOfZion/neon-wallet#813]
At first, I thought this was a Ledger-specific issue (#798), but after further testing, it seems to happen with saved wallets, too.

The issue happened initially when I tried to login with my Ledger. Upon clicking the "Use Ledger Nano S" button, the UI turned white, and there were multiple errors in the console:

```
TRANSACTION_HISTORY request action failed. Error: new BigNumber() not a number: GAS
at raise (http://localhost:3000/dist/bundle.js:32508:25)
    at http://localhost:3000/dist/bundle.js:32496:33
    at new BigNumber (http://localhost:3000/dist/bundle.js:31511:67)
    at toBigNumber (http://localhost:3000/dist/bundle.js:15311:10)
    at http://localhost:3000/dist/bundle.js:2047:177
    at Array.map (native)
    at _callee$ (http://localhost:3000/dist/bundle.js:2039:61)
    at tryCatch (http://localhost:3000/dist/bundle.js:128492:40)
    at Generator.invoke [as _invoke] (http://localhost:3000/dist/bundle.js:128730:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/dist/bundle.js:128544:21)
```

```
Uncaught TypeError: Cannot read property 'NEO' of null
    at mapAccountDataToProps (index.js:30)
    at Function.mapStateToProps [as mapToProps] (withData.js:38)
    at mapToPropsProxy (wrapMapToProps.js:43)
    at Function.detectFactoryAndVerify (wrapMapToProps.js:52)
    at mapToPropsProxy (wrapMapToProps.js:43)
    at handleFirstCall (selectorFactory.js:26)
    at pureFinalPropsSelector (selectorFactory.js:74)
    at Object.runComponentSelector [as run] (connectAdvanced.js:26)
    at Connect.initSelector (connectAdvanced.js:178)
    at new Connect (connectAdvanced.js:119)
```

I've seen the same issue occur when using a saved wallet, but it doesn't happen every time. I've seen it happen when switching from MainNet to TestNet, but that also works most of the time.

I'm only seeing the issue about 33% of the time.

I don't know if this correlation is causation yet, but it seems that the issue occurs when using Neoscan for requests like:

https://api.neoscan.io/api/main_net/v1/get_address_neon/XX
https://api.neoscan.io/api/main_net/v1/get_claimable/XX

whereas it works when using Neon wallet DB:

http://api.wallet.cityofzion.io/v2/address/history/XX
http://api.wallet.cityofzion.io/v2/address/balance/XX
http://api.wallet.cityofzion.io/v2/address/claims/XX

It seems that this Neoscan API call is used in both cases (success and failure scenarios):

https://api.neoscan.io/api/main_net/v1/get_balance/XX

Let me know if there are more details you need from me!

**Comment by mhuggins** [comment]
@brianlenz @dvdschwrtz This is due to a recent change to add load balancing.  The neoscan API is not returning things in a correct format.  I'm already on top of it. 😄

**Comment by brianlenz** [comment]
Sweet, I shouldda figured you guys were already on it 👍 Let me know if these reports become too annoying/redundant 😂

**Comment by mhuggins** [comment]
@brianlenz They're super helpful, I love them if you've got the time for them!

**Comment by brianlenz** [comment]
Cool, sounds good; as long as I'm not stepping on toes 👍
